---
#Tagger info
TaggerBin : 'tree-tagger/cmd/tree-tagger-french-utf8'
TaggerSeparator : \t
TagFile : 'config/frTTtag.yml'

#Database
#db : 'cConj'
#serveur : 'localhost'
#login : 'cconj'
#pass : 'cconj'
#port : ''
claco : 1
db : 'claroline_prod'
serveur : 'localhost'
login : 'claco'
pass : 'laurent'
port : ''
