---
#Tagger info
TaggerBin : 'tree-tagger/cmd/tree-tagger-french-utf8'
TaggerSeparator : \t
TagFile : 'config/frTTtag.yml'

#Intégration avec Claroline Connect (1 = oui 0 = non)
claco : 1

#Database
db : 'claroline_prod'
serveur : 'localhost'
login : 'claco'
pass : 'laurent'
port : ''
