---
#Tagger info
TaggerBin : 'tree-tagger/cmd/tree-tagger-french-utf8'
TaggerSeparator : \t
TagFile : 'config/frTTtag.yml'

#Database
db : 'cConj'
serveur : 'localhost'
login : 'cconj'
pass : 'cconj'
port : ''

#Database de Claroline Connect
dbClaco : 'claroline_prod'
serveurClaco : 'localhost'
loginClaco : 'claco'
passClaco : 'laurent'
portClaco : ''
