---
Verbe:
    VER:cond: conditionnel présent
    VER:futu: futur simple
    VER:impe: verb imperative
    VER:impf: imparfait
    VER:infi: infinitif
    VER:pper: participe passé
    VER:ppre: participe présent
    VER:pres: présent
    VER:simp: passé simple
    VER:subi: subjonctif imparfait
    VER:subp: subjonctif présent


